### ISSUE TITLE
Setting timeout from user-space program

### ISSUE THREAD

**Issue by amba** [dpenkler/linux-usbtmc#1]
The fixed timeout of 5 seconds has been a serious problem of the linux usbtmc driver. With our equipment, there are many cases where 5 seconds is either to long or too short.
Making it configurable via module_param() is a good thing, but requires reloading of the module and root permissions.

It would be better, if the timeout could be set by the user program. If I can do this with the Linux-GPIB library, why not with the linux USBTMC driver? ;)

**Comment by dpenkler** [comment]
Hi Simon,
Your are right. I will add an ioctl to set the timeout programmatically.
Thanks,
-Dave

**Comment by dpenkler** [comment]
Hi Simon,
I pushed a change for this. Please could you test it ?
thanks,
-Dave

**Comment by GuidoKiener** [comment]
Hi Dave,

It's a good idea to change the timeout with the new USBTMC488_IOCTL_TIMEOUT command. However I think we will need more flexibility and a device specific timeout value instead of just one global usb_timeout value. My first approach would be:
- usb_timeout is just the default value for each device instance
- For each device instance we have a specific timeout value that can be set with USBTMC488_IOCTL_SET_TIMEOUT. USBTMC488_IOCTL_GET_TIMEOUT returns the current timeout value. The timeout value is used for read and write operations.
- Other timeouts are maybe useful for the CLEAR and ABORT operations within reasonable ranges. But let us discuss and define these values after the next IVI meetings.

Regards 
Guido
