### ISSUE TITLE
Revert back to original driver?

### ISSUE THREAD

**Issue by rpoffen** [dpenkler/linux-usbtmc#4]
Is there a way to revert back to the original behavior? It appears that this is now incorporated in Centos 7.6, and breaks our existing software. It is not practical for us to change our code, existing applications must work without modification.
Any suggestions appreciated.

**Comment by GuidoKiener** [comment]
I'm sorry for this inconvenience. In general I agree that driver changes should not break existing applications. However there is one API change that we needed to do for future applications to provide a consistent API design.

_SRQ now sets EPOLLPRI instead of EPOLLIN since EPOLLIN is now reserved for asynchronous reads_
see [usb: usbtmc: Support Read Status Byte with SRQ per file](https://patchwork.kernel.org/patch/10531567/)

The previous patch was needed to add asynchronous I/O
[[v6,02/22] usb: usbtmc: Add ioctl for vendor specific write](https://patchwork.kernel.org/patch/10596939/)
[[v6,04/22] usb: usbtmc: Add ioctl for vendor specific read](https://patchwork.kernel.org/patch/10596917/)

Maybe there are other patches [https://github.com/torvalds/linux/commits/master/drivers/usb/class/usbtmc.c](https://github.com/torvalds/linux/commits/master/drivers/usb/class/usbtmc.c) that are affecting your application. At the moment I do not know which patches are integrated in Centos 7.6. Let me know your problem and I can try to help you to workaround it or to patch the kernel for future releases.

You also can send me a direct mail to usbtmc@kiener-muenchen.de

-Guido

**Comment by dpenkler** [comment]
Earlier drivers (pre 4.6 kernel.org release) did not implement .poll() so calling userspace poll() would return all the flags set. The drivers in subsequent releases do implement .poll() so when poll() is called and the condition does not occur in time a timeout is signalled.
